# Versi API yang didefinisikan
apiVersion: v1
# jenis objek kubernetes ConfigMap
kind: ConfigMap
#metadata ConfigMap
metadata:
  # nama ConfigMap
  name: mongo-config
# data sebagai file mongo.conf yang memiliki properti storage dengan key dbPath dan value /data/db
data:
  mongo.conf: |
    storage:
      dbPath: /data/db