# versi API yang didefinisikan
apiVersion: v1
# jenis objek Kubernetes Service
kind: Service
# metadata Service
metadata:
  # nama Service
  name: mongo-service
  labels:
    app: database
# spesifikasi Service
spec:
  ports:
  # port service yang diekspose
  - port: 27017
    protocol: TCP
  # selector untuk memilih pod yang akan dilayani service
  selector:
    app: database