# Versi API yang didefinisikan
apiVersion: v1
# jenis objek kubernetes Service
kind: Service
# metadata untuk service
metadata:
  # nama Service
  name: karsajobs-ui-services
  labels:
    app: frontend
# spesifikasi Service    
spec:
  type: NodePort
   # port Service yang diekspose
  ports:
  - port: 8000
  # selector untuk memilih pod yang akan dilayani service
  selector:
    app: frontend
  